### ISSUE TITLE
[Support Question] Getting the JJRobots app to work with custom code

### ISSUE THREAD

**Issue by FHeilmann** [jjrobots/B-ROBOT_EVO2#5]
Hi JJRobots team,
I recently stumbled upoin the B-Robot EVO 2 and I like the project very much. I wanted to cut down on hardware complexity and also increase processing power to add some new stuff, so I am trying to port the code to directly run on an ESP32 board.

I am struggling with getting data from the JJRobots control app into my code. I set up the WiFi hotspot to the best of my knowledge and, initially, simply set up a UDP listener to show me whether I am receiving something.

I also tested said receiver by sending UDP messages from my android phone to the ESP. Unfortunately, I am unable to intercept messages from the JJRobots control app.

Is there some sort of initialization phase that I need to perform, in order for the app to start sending control data to my ESP? Or does the app not send unless it receives telemetry data from the bot? Could you please tell me which IP address and port the app tries to send data to/receive from?

Thanks a lot for your assistance!

**Comment by mar0x** [comment]
Hi @jjrobots team and @FHeilmann,

I'm also interesting in getting the Android app source code.  Although there is an alternative [AndrOSC](https://github.com/ahmetkizilay/AndrOSC), which is looks promising, but does not works for me out of the box (send float numbers as strings).

Technically, B-ROBOT listens UDP 192.168.4.1:2222 and send back to UDP 192.168.4.2:2223.  For communication it uses [OSC](http://opensoundcontrol.org/spec-1_0) protocol. IP addresses is quite easy to change in B-ROBOT sources, but impossible to change in [JJrobots control APP](https://play.google.com/store/apps/details?id=jjrobots.jjrobots_002). This why it would be nice to get the App sources.

There is also [good recap of the current Apps status](http://forums.jjrobots.com/thread-1494.html), but response does not contains the information of Android app sources.

**Comment by mar0x** [comment]
Hi @FHeilmann,

Have you get the source code or no longer interested in this project?

**Comment by FHeilmann** [comment]
@mar0x no. I have gotten no response and just closed the issue due to inactivity.
